apiVersion: skaffold/v2beta18
kind: Config

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: backend
        context: backend
        sync:
          manual:
          - src: 'src/**/*.rs'
            dest: .
